version: "2"
services:
    proxy:
        image: nginx:1.13.6-alpine
        container_name: romnum_proxy
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available/default:/etc/nginx/conf.d/default.conf
            - ../frontend:/usr/share/nginx/html
            - /var/log/nginx:/var/log/nginx
        ports:
            - 80:80
            - 443:443
        depends_on: 
            - api

    api:
        image: keymetrics/pm2:7
        container_name: romnum_api
        volumes:
            - ../api:/app
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=test
        command: "pm2-dev start --auto-exit --env test process.yml" 